apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-service.fullname" . }}-config
  labels:
    app: {{ include "inventory-service.name" . }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
  ASPNETCORE_URLS: {{ .Values.env.ASPNETCORE_URLS | quote }}
  Logging__LogLevel__Default: {{ .Values.logging.level | quote }}
