apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-service.fullname" . }}-secret
  labels:
    app: {{ include "inventory-service.name" . }}
type: Opaque
data:
  ConnectionStrings__DefaultConnection: {{ printf "Host=%s;Port=%s;Database=%s;Username=%s;Password=changeme" .Values.postgresql.host (toString .Values.postgresql.port) .Values.postgresql.database .Values.postgresql.username | b64enc | quote }}
